version: '2'

services:

  nginx:
    volumes:
      - ./build/nginx/config/etc/letsencrypt/live/app:/etc/letsencrypt/live/app

#  db:
#    ports:
#      - 3306:3306

  #phpmyadmin:
    #environment:
    #  - VIRTUAL_HOST=minetest-bower.afi.127.0.0.1.xip.io
    #networks:
    #  - default
    #  - nginx-proxy
    #volumes:
    #  - ./build/phpmyadmin/etc/phpmyadmin/config.dev.inc.php:/etc/phpmyadmin/config.user.inc.php

